#Configuarar los contenedores

services:
  database:
    image: mysql:8
    container_name: sgu-database #Nombre del contenedor de la base de datos
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgu_db
    ports:
      - "3307:3306"
    networks:
      - sgu-net
    volumes:
      - sgu-volume:/var/lib/mysql

  frontend:
    image: client:1.0-sgu
    build:
      context: ./frontend
      args:
        API_HOST: backend
        API_PORT: 8081
        API_BASE: /sgu-api
    container_name: sgu-frontend #Nombre del contenedor del frontend
    ports:
      - "3000:80"
    networks:
      - sgu-net
    depends_on:
      - backend

  backend:
    image: server:1.0-sgu
    build:
      context: ./backend
    container_name: sgu-backend
    environment:
      SERVER_PORT: 8080
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: sgu_db
      DB_USER: root
      DB_PASS: root
    ports:
      - "8081:8080"
    networks:
      - sgu-net
    depends_on:
      - database


# aqui se pueden definir las redes entre contenedores
networks:
  sgu-net:
    driver: bridge

# aqui configuro los volumenes que ocupan los contenedores
volumes:
  sgu-volume:
    driver: local


